# fly.toml app configuration file generated for lkw123-fastapi on 2024-08-23T20:10:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lkw123-fastapi'
primary_region = 'iad'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
